### ISSUE TITLE
[BUG] Quickstart timer no longer works after update

### ISSUE THREAD

**Issue by notdeadyett** [linuxserver/docker-babybuddy#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking on the quick start timer button on the main page does nothing.

### Expected Behavior

Clicking on the quick start timer button should start a timer.

### Steps To Reproduce

Open babybuddy
Click quick start timer button
Nothing happens

### Environment

```markdown
- OS: Linux
- How docker service was installed: Via command-line
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=babybuddy \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,https://babybuddy.domain.com \
  -p 8000:8000 \
  -v /path/to/appdata:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/babybuddy:latest
```

### Container logs

```bash
No errors in log
```

**Comment by aptalca** [comment]
I just tested it on my instance, works fine.

**Comment by cdubz** [comment]
@notdeadyett if there is a bug here it probably belongs over at https://github.com/babybuddy/babybuddy. Could you create an issue there with more details?

**Comment by cdubz** [comment]
FYI @notdeadyett this issue has been fixed in babybuddy/babybuddy/issues/677 (and is in the v2.0.1 just released).
